import vine from '@vinejs/vine'

export const createClientValidator = vine.compile(
  vine.object({
    email: vine.string().email(),
    password: vine.string().minLength(8).optional(),
    civilite: vine.string().optional(),
    nom: vine.string().minLength(2).maxLength(100),
    prenom: vine.string().minLength(2).maxLength(100),
    dateNaissance: vine.string().optional(),
    lieuNaissance: vine.string().optional(),
    nationalite: vine.string().optional(),
    telephone: vine.string().optional(),
    telephoneSecondaire: vine.string().optional(),
    adresseLigne1: vine.string().optional(),
    adresseLigne2: vine.string().optional(),
    codePostal: vine.string().optional(),
    ville: vine.string().optional(),
    pays: vine.string().optional(),
    type: vine.enum(['particulier', 'institutionnel']).optional(),
    societeNom: vine.string().optional(),
    societeSiret: vine.string().optional(),
    societeFonction: vine.string().optional(),
    peutUploader: vine.boolean().optional(),
    peutDemanderRdv: vine.boolean().optional(),
    accesDocumentsSensibles: vine.boolean().optional(),
    notifEmailDocument: vine.boolean().optional(),
    notifEmailEvenement: vine.boolean().optional(),
    actif: vine.boolean().optional(),
    notesInternes: vine.string().optional(),
    tags: vine.array(vine.string()).optional(),
    sourceAcquisition: vine.string().optional(),
  })
)

export const updateClientValidator = vine.compile(
  vine.object({
    email: vine.string().email().optional(),
    civilite: vine.string().optional(),
    nom: vine.string().minLength(2).maxLength(100).optional(),
    prenom: vine.string().minLength(2).maxLength(100).optional(),
    dateNaissance: vine.string().optional(),
    lieuNaissance: vine.string().optional(),
    nationalite: vine.string().optional(),
    telephone: vine.string().optional(),
    telephoneSecondaire: vine.string().optional(),
    adresseLigne1: vine.string().optional(),
    adresseLigne2: vine.string().optional(),
    codePostal: vine.string().optional(),
    ville: vine.string().optional(),
    pays: vine.string().optional(),
    type: vine.enum(['particulier', 'institutionnel']).optional(),
    societeNom: vine.string().optional(),
    societeSiret: vine.string().optional(),
    societeFonction: vine.string().optional(),
    peutUploader: vine.boolean().optional(),
    peutDemanderRdv: vine.boolean().optional(),
    accesDocumentsSensibles: vine.boolean().optional(),
    notifEmailDocument: vine.boolean().optional(),
    notifEmailEvenement: vine.boolean().optional(),
    actif: vine.boolean().optional(),
    notesInternes: vine.string().optional(),
    tags: vine.array(vine.string()).optional(),
    sourceAcquisition: vine.string().optional(),
  })
)
